services:
  postgres:
    image: postgres:16
    container_name: internal_company_postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: internal_user
      POSTGRES_PASSWORD: internal_password
      POSTGRES_DB: internal_company_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
